### ISSUE TITLE
Add option to exclude output of certain filters

### ISSUE THREAD

**Issue by calchoo** [bcgsc/biobloom#27]
Hi,

One of our use cases involves running a bunch of filters to detect non human reads in our samples. This involves running the sample with a bunch of microbial filters and a human filter. As we expect, the vast majority end up in the human bin which is of no interest in this case. 

Could we get an option to exclude the hits that hit a certain filter from the output?

**Comment by JustinChu** [comment]
in the develop branch I added an inverse (-n) parameter, let me know if that if it works the way you want.
