### ISSUE TITLE
Fails with error: invalid variable name: `–-with-boost'

### ISSUE THREAD

**Issue by conchoecia** [bcgsc/biobloom#28]
Is the `--with-boost` option actually implemented in `configure`? I will post if I find a solution

`erenna:[/usr/local/bin/biobloom]$ sudo ./configure –-with-boost=/usr/lib/x86_64-linux-gnu/ --prefix=/usr/local/bin/biobloom/bin && sudo make install`
`configure: error: invalid variable name: `–-with-boost'`

**Comment by conchoecia** [comment]
The problem was from copying the `--with-boost` from the html of the github page. Maybe check that there are actually two hyphens and not another character from another keyboard?

**Comment by JustinChu** [comment]
Thanks for the report. It wasn't the right character somehow. Funny how things like that can pop up. It should be fixed in the readme now.
