### ISSUE TITLE
Sdsl issue ? 

### ISSUE THREAD

**Issue by nektem** [bcgsc/biobloom#32]
Hi, I'm just an undergraduate student dipping his toes in bioinformatics and I must make this run for an obligatory assignment.  
However I have an issue that I haven't seen reported here so I am assuming there is something that I am missing something obvious.
I run ./configure without any problems however when I run make I run into the following issue : 
The program can't seem to find the sdsl files even though I have installed them properly.  How can I solve this ? 

Thanks in advance !

![screenshot 4](https://user-images.githubusercontent.com/33673942/39656249-30995608-5007-11e8-831c-c7d41c6e6868.png)

**Comment by JustinChu** [comment]
Yeah, that is my bad I haven't added checks for sdsl yet in the current version:
https://github.com/bcgsc/biobloom/blob/4816abe0b9f3726f4d613f719cf8157d6fb16cd5/configure.ac#L70

In the meantime, it should be fine so long as you properly install sdsl.
```{bash}
git clone https://github.com/simongog/sdsl-lite.git
cd sdsl-lite
./install.sh
```

**Comment by JustinChu** [comment]
Check added in master branch.
