### ISSUE TITLE
Question for installation

### ISSUE THREAD

**Issue by lh12565** [bcgsc/biobloom#37]
Hi, Justin Chu
When I make the biobloom, it has the following error:

MIBFGen.hpp:834:46: error: use of deleted function std::basic_ofstream<char>::basic_ofstream(const std::basic_ofstream<char>&)...
/usr/include/c++/4.8.2/fstream:599:11: error: use of deleted function std::basic_ostream<char>::basic_ostream(const std::basic_ostream<char>&)....
.....

How do I solve this problem?
Thanks!

**Comment by JustinChu** [comment]
Hi, can you try the latest commit 5c028884f41147e7bc0f654d8188d85ee017c0c1. That function is technically unused anyway.

**Comment by lh12565** [comment]
It works. You are right. My gcc is 4.8.5. Thanks!
