### ISSUE TITLE
2.0.12 tarball does not include configure

### ISSUE THREAD

**Issue by sjackman** [bcgsc/biobloom#4]
The 2.0.12 tarball does not include configure. I'm okay with that, but you'll need to update the build instructions if it's intentional.

**Comment by JustinChu** [comment]
Added tarball, also included changelog for good measure.

**Comment by sjackman** [comment]
`autogen.sh` is missing from this tarball.

**Comment by sjackman** [comment]
`README.md` is also missing from this tarball.

**Comment by sjackman** [comment]
Please add `README.md` to `dist_doc_DATA`. See https://github.com/bcgsc/abyss/blob/master/Makefile.am#L15
Add `autogen.sh` to `EXTRA_DIST`

**Comment by JustinChu** [comment]
if configure is already generated in the tarball, why should `autogen.sh` be included?

**Comment by JustinChu** [comment]
README.md and README.html included in tarball

**Comment by sjackman** [comment]
So that users can regenerate `configure` if necessary after modifying `configure.ac`.

**Comment by JustinChu** [comment]
Added.
1f1e83e23620d7541607db26f66e5262139a491b

Thanks Shaun
