### ISSUE TITLE
Project page link does not link to latest release

### ISSUE THREAD

**Issue by jplaverdure** [bcgsc/biobloom#47]
Hi, at the top of the github repo, you provide this link:  
http://www.bcgsc.ca/platform/bioinfo/software/biobloomtools  

Unfortunately, it links to 2.1.1 as being the current release, which is no longer true.
Please update as this is confusing to less savvy users.

Thanks !

**Comment by JustinChu** [comment]
That is confusing in retrospect. I intended users to use the link to the github in the description. To prevent confusion I've removed the releases from the bcgsc website so they have to come here to download it.
