### ISSUE TITLE
Issue compiling release 2.3.2

### ISSUE THREAD

**Issue by jplaverdure** [bcgsc/biobloom#48]
Hello,

We ran into issues trying to compile the files from the 2.3.2 release obtained from github here:
https://github.com/bcgsc/biobloom/releases/tag/2.3.2  
We were working off the .tar.gz archive

Here's the error we got:
```
Making all in BioBloomCategorizer
make[2]: Entering directory `/u/jpl/Downloads/biobloomtools-2.3.2/BioBloomCategorizer'
g++ -DHAVE_CONFIG_H -I. -I..  -I/u/jpl/Downloads/biobloomtools-2.3.2/BioBloomCategorizer -I/u/jpl/Downloads/biobloomtools-2.3.2/Common -I/u/jpl/Downloads/biobloomtools-2.3.2 -I/u/jpl/Downloads/biobloomtools-2.3.2    -std=c++11  -Wall -Wextra -Werror  -fopenmp -g -O2 -MT biobloomcategorizer-Options.o -MD -MP -MF .deps/biobloomcategorizer-Options.Tpo -c -o biobloomcategorizer-Options.o `test -f 'Options.cpp' || echo '/u/jpl/Downloads/biobloomtools-2.3.2/BioBloomCategorizer/'`Options.cpp
Options.cpp:18:1: error: ‘OutType’ does not name a type
 OutType outputType = NONE;
 ^

```
Compilation went smoothy with code checked out from the master branch so we are using that for now. However, others might run into similar issues and having a specific release version is always nice when the time comes to write a paper :).

Thanks for all the hard work !

**Comment by JustinChu** [comment]
That error is a bit strange considering that header hasn't been changed. At any rate I'm glad the master branch works for you.

I will release a new version at some point, but in the mean time the `--version` option should report a modified version ID that is derived from the last tagged version and the git commit ID which can serve as a unique identifier to determine the version of BBT used.

**Comment by YimingWoo** [comment]
Hi, Justin, I think the problem may be due to a mistype in BioBloomCategorizer/Options.cpp, the include line should have been `#include "Options.h"` other than `#include <Options.h>` , while the former seems to solve the compiling.
