### ISSUE TITLE
samtools faidx problem

### ISSUE THREAD

**Issue by vardaofthevalier** [bcgsc/biobloom#8]
I'm attempting to run biobloommaker on an indexed fasta file that I created with "samtools faidx ..."  using a variation of the following command:

```
biobloommaker -p prefix indexed_fasta.fa.fai
```
But I'm getting the following message:

```
Fasta files must be indexed. Use samtools faidx.
```

I'm a software engineer by profession working on developing bioinformatics workflow tools for one of NCI's Cancer Genomics Cloud pilot projects, so due to having only a superficial understanding of bioinformatics tools in general, I have a feeling there may be something I've missed somewhere that's causing me to run into this issue.  Any suggestions or advice about what I might be doing wrong would be much appreciated.  I'd be happy to provide more information upon request.

**Comment by vardaofthevalier** [comment]
Actually, I think I just figured it out.  I had assumed that the input file that I was supposed to be passing in on the command line was the ".fai" file, but just realized that I should have been passing in the actual fasta file that was indexed, but also making sure that the ".fai" file was available in the same directory.  I tried rerunning the command I mentioned above as:

```
biobloommaker -p prefix fasta_file.fa
```

And as long as the ".fai" file is present in the same directory it seems to work.  Am I correct in this assumption, or is there more to it that that?

**Comment by JustinChu** [comment]
This is correct. biobloommaker looks for a file with .fai extension appended to the fasta file used in normal filter creation. It used the index to acquire the number of expected k-mers in the file.

This has been a issue before. It seems that it might be a good idea for me just to either automatically generate a fai file or manually parse the file once when the fai file is missing.

Just to be clear, an index is not needed for biobloomcategorizer.
