### ISSUE TITLE
configure: error: Requires sdsl

### ISSUE THREAD

**Issue by adrienlemeur** [bcgsc/biobloom#82]
Hello,

Just having a little issue with the installation. Of course, the issue is that I installed the dependencies but BBT won't find sdsl not matter where I try to put it. Thank you ! Once I get this solved I will try later to write a docker recipe with the latest version :D

> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
> checking for gawk... no
> checking for mawk... mawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking for ranlib... ranlib
> checking for g++... g++
> checking whether the C++ compiler works... yes
> checking for C++ compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C++ compiler... yes
> checking whether g++ accepts -g... yes
> checking whether make supports the include directive... yes (GNU style)
> checking dependency style of g++... gcc3
> checking for gcc... gcc
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking whether gcc understands -c and -o together... yes
> checking dependency style of gcc... gcc3
> checking for dlopen in -ldl... yes
> checking how to run the C preprocessor... gcc -E
> checking for grep that handles long lines and -e... /usr/bin/grep
> checking for egrep... /usr/bin/grep -E
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking for size_t... yes
> checking how to run the C++ preprocessor... g++ -E
> checking boost/property_tree/ptree.hpp usability... yes
> checking boost/property_tree/ptree.hpp presence... yes
> checking for boost/property_tree/ptree.hpp... yes
> checking boost/property_tree/ini_parser.hpp usability... yes
> checking boost/property_tree/ini_parser.hpp presence... yes
> checking for boost/property_tree/ini_parser.hpp... yes
> checking btl_bloomfilter/BloomFilter.hpp usability... yes
> checking btl_bloomfilter/BloomFilter.hpp presence... yes
> checking for btl_bloomfilter/BloomFilter.hpp... yes
> checking zlib.h usability... yes
> checking zlib.h presence... yes
> checking for zlib.h... yes
> checking google/dense_hash_map usability... yes
> checking google/dense_hash_map presence... yes
> checking for google/dense_hash_map... yes
> checking sdsl/bit_vector_il.hpp usability... no
> checking sdsl/bit_vector_il.hpp presence... no
> checking for sdsl/bit_vector_il.hpp... no
> configure: error: Requires sdsl

**Comment by lcoombe** [comment]
Hello @adrienlemeur,

Have you tried installing BBT using conda? (https://anaconda.org/bioconda/biobloomtools) We often recommend that, since it tends to be more straightforward.

If you want to install from source - how did you install sdsl? Have you tried using the option `--with-sdsl` to specify the location of the installation?

Thanks for your interest in BBT!

**Comment by adrienlemeur** [comment]
Ah that was it for conda ! I always take for granted the channels are set ! Thanks, it worked at last !

I would like to integrate BBT in a Nextflow pipeline in the near future so I hope it will go well with source installation.

**Comment by lcoombe** [comment]
Excellent, glad to hear the conda install is working for you now! 
I realize we don't have conda install mentioned on the README, so I'll add that as well (including the channels)!
