### ISSUE TITLE
Reproducible outputs

### ISSUE THREAD

**Issue by vdechand** [bcgsc/biobloom#85]
Hello,

is there a way to make the output fastq files reproducible, except for running BBT with only 1 thread?

**Comment by lcoombe** [comment]
Hi @vdechand,

By "reproducible", do you mean consistent ordering of the output fastq files? The reads in the output files should be the same between runs but yes, the order of those reads may vary when you use multiple threads.

**Comment by vdechand** [comment]
Hi Lauren,

thanks! Turns out I messed up the sorting of the categorized fastq files.... 
Using `NGSUtils/fastqutils sort` I get exact same output files as required.

**Comment by lcoombe** [comment]
Glad to hear it, thanks for the update!
