### ISSUE TITLE
Biobloom categorizer dies in a misterious way

### ISSUE THREAD

**Issue by KristinaGagalova** [bcgsc/biobloom#86]
Hi

I am running biobloomcategorizer with multiple filters for contamination screening.
This is the error I am having
```
Command error:
  Min score threshold: 0.15
  Starting to Load Filters.
  Loaded Filter: Univec
  Loaded Filter: taxid27482
  Loaded Filter: taxid4513
  Loaded Filter: plastid.1.rna
  error: `biobloom-filters/taxid4890.bf': Success
```
FYI - taxid4890 is the largest filter I have. 

This is the command:
```
biobloomcategorizer -p reads    -t 32         -e         -i         -f "Univec.bf taxid27482.bf taxid4513.bf plastid.1.rna.bftaxid4890.bf taxid30262.bf taxid6946.bf" read_R1.fastq.gz read_R2.fastq.gz
```

BBT specs
```
biobloomtools=2.3.5
```

I assigned quite a lot of memory on slurm
```
CPU Utilized: 00:00:23
CPU Efficiency: 0.38% of 01:40:16 core-walltime
Job Wall-clock time: 00:00:47
Memory Utilized: 97.75 GB
Memory Efficiency: 13.96% of 700.00 GB
```

Do you have any idea what could that be? 
Thank you in advance

**Comment by lcoombe** [comment]
Hi Kristina,

Not sure if it's just how you copied your command but I see that there isn't a space between what I assume is two different Bloom filters?
```
plastid.1.rna.bftaxid4890.bf
```

**Comment by KristinaGagalova** [comment]
Hi @lcoombe 
That's not the issue, it's just a typo while removing some metadata from the script. I am using a nextflow command which formats everything properly.

**Comment by KristinaGagalova** [comment]
Hi @lcoombe 
I rerun the biobloom make and now it's running. Even if I had both the ```.bf``` and the ```*txt``` files, looks like the filter was not generated properly for some reason, possibly some file system issues. 
Thank you for the suggestions! I am closing the ticket

**Comment by lcoombe** [comment]
Great, glad to hear it's working now!
