### ISSUE TITLE
Why biobloomcategorizer does not output fastq.gz file as expected

### ISSUE THREAD

**Issue by Ivy-ops** [bcgsc/biobloom#88]
Hi Developer,

According to the description of the biobloomcategorizer, it should output fastq.gz files. 
`The size of the output is proportional to the input since the results need to be stored. The contents of the output fastq files can be compressed directly as needed with the --gz option however (which is what zlib was needed in the installation).`

I have zlib installed. However, my code below only generates *_summary.tsv files. Could you please help me identify if there’s anything wrong with my implementation? Thank you!

`biobloomcategorizer -t 16 -p ${sample_name} -f human.bf -e -i --gz S1_R1.fastq.gz S1_R2.fastq.gz`

**Comment by JustinChu** [comment]
Sorry for the confusion by default it does not out filtered files. Add in `--fq` in your command.
